apiVersion: v1
kind: Secret
metadata:
  name: s3-creds
stringData:
  CLUSTER_NAME: {{ .Values.clusterName }}
  S3_URL: {{ .Values.s3.url }} 
  S3_ACCESS_KEY: {{ .Values.s3.access_key }} 
  S3_SECRET_KEY: {{ .Values.s3.secret_key }} 
  S3_BUCKET: {{ .Values.s3.bucket }} 
