apiVersion: v1
kind: Secret
metadata:
  name: s3-creds
data:
  CLUSTER_NAME: {{ .Values.clusterName | b64enc }}
  S3_URL: {{ .Values.s3.url | b64enc }}
  S3_ACCESS_KEY: {{ .Values.s3.accessKey | b64enc }}
  S3_SECRET_KEY: {{ .Values.s3.secretKey | b64enc }}
  S3_BUCKET: {{ .Values.s3.bucket | b64enc }}
